# Generated by Django 3.0.4 on 2020-03-22 09:55

from django.db import migrations, models
import django.db.models.deletion
import workouts.models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_auto_20200322_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='gif',
            field=models.FileField(blank=True, null=True, upload_to=workouts.models.exercise_gif_path),
        ),
        migrations.AlterField(
            model_name='workoutexercise',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workouts.Exercise'),
        ),
    ]
